platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: SpringBootSimpleRest

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    git clone SpringBootSimpleRest built-project
    cd built-project
    ls -la    
    mvn package
    ls -la
    cd target
    ls -la
    cd ..
    chmod 777 target
    cd target
    mv springbootsimplerest-0.0.4-SNAPSHOT.jar demo.jar
    ls -la
    cd ..
    git config --global user.email "dande@miraclesoft.com"
    git config --global user.name "dhaneshande"
    #git init
    git add .
    git commit -m "Bumped date"
    git push origin master
    #cp ./target/springbootsimplerest-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
    #cp Dockerfile ../built-project
    #ls -la
