resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/dhaneshande/SpringBootPipelineStoringJarToGit.git
    branch: master
jobs:
- name: job-deploy-app
  serial: true
  plan:
  - get: SpringBootSimpleRest
  - task: build
    file: SpringBootSimpleRest/ci/build.yml
  - task: build-project
    file: SpringBootSimpleRest/ci/tag-files.yml
    params: {save: true}
  - put: SpringBootSimpleRest
    params: {repository: built-project}
